/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRegulationRouteImport } from './routes/ai-regulation'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as MarketingConsentRouteImport } from './routes/marketing-consent'
import { Route as PersonalDataConsentRouteImport } from './routes/personal-data-consent'
import { Route as PersonalDataRequestsRouteImport } from './routes/personal-data-requests'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as CatalogSlugRouteImport } from './routes/catalog_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRegulationRoute = AiRegulationRouteImport.update({
  id: '/ai-regulation',
  path: '/ai-regulation',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingConsentRoute = MarketingConsentRouteImport.update({
  id: '/marketing-consent',
  path: '/marketing-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDataConsentRoute = PersonalDataConsentRouteImport.update({
  id: '/personal-data-consent',
  path: '/personal-data-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDataRequestsRoute = PersonalDataRequestsRouteImport.update({
  id: '/personal-data-requests',
  path: '/personal-data-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog_/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-regulation': typeof AiRegulationRoute
  '/catalog': typeof CatalogRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/marketing-consent': typeof MarketingConsentRoute
  '/personal-data-consent': typeof PersonalDataConsentRoute
  '/personal-data-requests': typeof PersonalDataRequestsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/catalog/$slug': typeof CatalogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-regulation': typeof AiRegulationRoute
  '/catalog': typeof CatalogRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/marketing-consent': typeof MarketingConsentRoute
  '/personal-data-consent': typeof PersonalDataConsentRoute
  '/personal-data-requests': typeof PersonalDataRequestsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/catalog/$slug': typeof CatalogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-regulation': typeof AiRegulationRoute
  '/catalog': typeof CatalogRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/marketing-consent': typeof MarketingConsentRoute
  '/personal-data-consent': typeof PersonalDataConsentRoute
  '/personal-data-requests': typeof PersonalDataRequestsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/catalog_/$slug': typeof CatalogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-regulation'
    | '/catalog'
    | '/cookie-policy'
    | '/marketing-consent'
    | '/personal-data-consent'
    | '/personal-data-requests'
    | '/privacy-policy'
    | '/catalog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-regulation'
    | '/catalog'
    | '/cookie-policy'
    | '/marketing-consent'
    | '/personal-data-consent'
    | '/personal-data-requests'
    | '/privacy-policy'
    | '/catalog/$slug'
  id:
    | '__root__'
    | '/'
    | '/ai-regulation'
    | '/catalog'
    | '/cookie-policy'
    | '/marketing-consent'
    | '/personal-data-consent'
    | '/personal-data-requests'
    | '/privacy-policy'
    | '/catalog_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRegulationRoute: typeof AiRegulationRoute
  CatalogRoute: typeof CatalogRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  MarketingConsentRoute: typeof MarketingConsentRoute
  PersonalDataConsentRoute: typeof PersonalDataConsentRoute
  PersonalDataRequestsRoute: typeof PersonalDataRequestsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-regulation': {
      id: '/ai-regulation'
      path: '/ai-regulation'
      fullPath: '/ai-regulation'
      preLoaderRoute: typeof AiRegulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-consent': {
      id: '/marketing-consent'
      path: '/marketing-consent'
      fullPath: '/marketing-consent'
      preLoaderRoute: typeof MarketingConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-data-consent': {
      id: '/personal-data-consent'
      path: '/personal-data-consent'
      fullPath: '/personal-data-consent'
      preLoaderRoute: typeof PersonalDataConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-data-requests': {
      id: '/personal-data-requests'
      path: '/personal-data-requests'
      fullPath: '/personal-data-requests'
      preLoaderRoute: typeof PersonalDataRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog_/$slug': {
      id: '/catalog_/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRegulationRoute: AiRegulationRoute,
  CatalogRoute: CatalogRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  MarketingConsentRoute: MarketingConsentRoute,
  PersonalDataConsentRoute: PersonalDataConsentRoute,
  PersonalDataRequestsRoute: PersonalDataRequestsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  CatalogSlugRoute: CatalogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
